In [167]:
import numpy as np

In [21]:
a = np.array([1,2,3])

In [22]:
print(a)

[1 2 3]


In [23]:
a

array([1, 2, 3])

In [24]:
a[0]

1

In [25]:
a[1]

2

## 3 Main benifits of Numpy array over a python list
1. Less Memory
2. Fast
3. Convinent

### Proof of Lesss Memory


In [30]:
# Python List
import sys
l = range(1000)
print(sys.getsizeof(5) * len(l)) 

28000


In [36]:
# Numpy array
array = np.arange(1000)
print(array.size * array.itemsize)

8000


### Numpy is fast and convinent compared to Native python list


In [38]:
import time

In [39]:
SIZE = 1000000

In [40]:
l1 = range(SIZE)
l2 = range(SIZE)

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

In [42]:
# Python List
start = time.time()
result = [(x+y) for x, y in zip(l1, l2)]
print("Python list took", (time.time() - start) * 1000 )

Python list took 140.00272750854492


In [43]:
# Numpy array
start = time.time()
result = a1 + a2
print("Number array took", (time.time() - start)*1000)

Number array took 21.355628967285156


In [50]:
a1 = np.arange(5)
a2 = np.arange(10, 15)


In [51]:
print("a1 = ", a1)
print("a2 = ", a2)

a1 =  [0 1 2 3 4]
a2 =  [10 11 12 13 14]


In [52]:
a1 + a2

array([10, 12, 14, 16, 18])

In [53]:
a2 - a1

array([10, 10, 10, 10, 10])

In [54]:
a1 * a2

array([ 0, 11, 24, 39, 56])

In [55]:
a2 / a1

/var/folders/38/2n6nwrx1587frtx3f7j3k9tw0000gn/T/ipykernel_12751/73751550.py:1: RuntimeWarning: divide by zero encountered in divide
  a2 / a1


array([        inf, 11.        ,  6.        ,  4.33333333,  3.5       ])

## Numpy basic array Operations

In [56]:
a = np.array([5,6,7])
print(a[0])
print(a[1])

5
6


In [57]:
a = np.array([[1,2], [3,4], [5,6]])

In [59]:
# dimentions
a.ndim

2

In [61]:
# byte size of each element
a.itemsize

8

In [62]:
# Datatype 
a.dtype

dtype('int64')

In [63]:
a = np.array([[1,2], [3,4], [5,6]], dtype = np.float64)

In [64]:
a


array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [66]:
# total elements
a.size

6

In [67]:
a.itemsize

8

In [68]:
a.shape

(3, 2)

In [69]:
a = np.array([[1,2], [3,4], [5,6]], dtype=complex)

In [70]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [71]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [72]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [73]:
l = range(5)

In [74]:
l

range(0, 5)

In [75]:
l = np.arange(1,5)

In [76]:
l

array([1, 2, 3, 4])

In [78]:
np.arange(1,5,2)

array([1, 3])

In [80]:
# Generate 10 numbers which are linerly spaced
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [83]:
a = np.array([[1,2], [3,4], [5,6]])

In [85]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [86]:
np.shape(a)

(3, 2)

In [87]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [89]:
a.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [90]:
a.reshape(6,1)


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [96]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [99]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
a.min()

1

In [101]:
a.max()

6

In [102]:
a.sum()

21

In [103]:
a.sum(axis=0)

array([ 9, 12])

In [104]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [105]:
a.sum(axis=0)

array([ 9, 12])

In [106]:
a.sum(axis=1)

array([ 3,  7, 11])

In [107]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [108]:
np.std(a)

1.707825127659933

In [110]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

In [111]:
a + b

array([[ 6,  8],
       [10, 12]])

In [112]:
a.dot(b)

array([[19, 22],
       [43, 50]])

# Indexing and Slicing

In [117]:
# Python List
n = [6, 7, 8]

In [114]:
n[0:2]

[6, 7]

In [115]:
n[-1]

8

In [116]:
a = np.array([6,7,8])

In [118]:
# Numpy Array
a = np.array([6,7,8])


In [119]:
a[0:2]

array([6, 7])

In [120]:
a[-1]


8

In [121]:
a = np.array([[6,7,9], [1, 2, 3], [9, 3, 2]])

In [122]:
a

array([[6, 7, 9],
       [1, 2, 3],
       [9, 3, 2]])

In [123]:
a[1, 2]

3

In [130]:
a[0: 2, 2]

array([9, 3])

In [131]:
a[-1]

array([9, 3, 2])

In [132]:
a[-1, 0:2]

array([9, 3])

In [133]:
a[:, 1:3]

array([[7, 9],
       [2, 3],
       [3, 2]])

In [134]:
for cell in a.flat:
    print(cell)

6
7
9
1
2
3
9
3
2


## Stacking

In [135]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)

In [136]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [137]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [139]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [140]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [141]:
a = np.arange(30).reshape(2,15)

In [142]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [143]:
np.hsplit(a, 3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [144]:
np.vsplit(a, 2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [145]:
a = np.arange(12).reshape(3,4)

In [146]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [147]:
b = a > 4

In [148]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [149]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [150]:
a[b] = -1

In [151]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

## Iterate Numpy array

In [152]:
a = np.arange(12).reshape(3,4)

In [153]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [156]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [157]:
for cell in a.flatten():
    print(cell)
    

0
1
2
3
4
5
6
7
8
9
10
11


In [159]:
for x in np.nditer(a, order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [160]:
for x in np.nditer(a, order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [162]:
for x in np.nditer(a, order='F', flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [164]:
a = np.arange(12).reshape(3,4)
b = np.arange(3, 15,4).reshape(3,1)

In [165]:
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 3]
 [ 7]
 [11]]


In [166]:
# Iterating over two arrays at a time
for x,y in np.nditer([a,b]):
    print(x, y)

0 3
1 3
2 3
3 3
4 7
5 7
6 7
7 7
8 11
9 11
10 11
11 11
